version: '3'
services:
  python-api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    networks: 
      - app-network
  react-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks: 
      - app-network
networks: 
  app-network:
    driver: bridge